sudo: required
services:
        - docker
before_install:
        - docker build -t swati211/docker-react -f Dockerfile.dev .
script:
        - docker run swati211/docker-react npm run test -- --coverage        

